name: Node CI

on: push

jobs:
  build_rund:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install, build, test
      run: |
        npm install
        npm start
      env:
        CI: true
