name: Node CI

on: push

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and start
        run: npm ci
      - run: npm run start
